replicaCount: 1

# this is necessary in order to support rancher's default system registry
global:
  cattle:
    systemDefaultRegistry: ""

rbac:
  useStaticUser: true

image:
  registry: "ghcr.io"
  repository: "loft-sh/vcluster-rancher-operator"
  tag: ""

fleet:
  defaultWorkspace: "fleet-default"
  projectUIDToWorkspaceMappings: {}

# syncLabels syncs labels from the vcluster service to it corresponding cluster objects
# includeKeys and excludeKeys support key-prefixes in the format of "<key>*", for example "org.company/*". "*" is also supported.
syncLabels:
  includeKeys: []
  excludeKeys: []
