replicaCount: 1

# this is necessary in order to support rancher's default system registry
global:
  cattle:
    systemDefaultRegistry: ""

rbac:
  useStaticUser: true

image:
  registry: "ghcr.io"
  repository: "loft-sh/vcluster-rancher-operator"
  tag: ""
